### ISSUE TITLE
intuitive play button labelling

### ISSUE THREAD

**Issue by davidderoure** [rncm-prism/PRiSM-MusicGestureRecognition#2]
The button to play back the recordings of gestures works fine, but it doesn't say "Play" before you hit it.

**Comment by davidderoure** [comment]
It takes time between hitting record and then picking up and playing an instrument. I wonder if the start of the recording could be triggered by the beginning of the audio (or if the onset of audio could cause silence to be deleted up to that point, either live or later).

**Comment by HongshuoFan** [comment]
> The button to play back the recordings of gestures works fine, but it doesn't say "Play" before you hit it.

Maybe reversing the  "Play" and "Stop" signs can help?

**Comment by HongshuoFan** [comment]
> It takes time between hitting record and then picking up and playing an instrument. I wonder if the start of the recording could be triggered by the beginning of the audio (or if the onset of audio could cause silence to be deleted up to that point, either live or later).

That's a good idea, I can add it to the next version. or maybe give 3 seconds countdown after hitting the "record" button?

**Comment by HongshuoFan** [comment]
Updated in the [v0.25 release ](https://github.com/rncm-prism/PRiSM-MusicGestureRecognition/releases/tag/v0.25)

**Comment by HongshuoFan** [comment]
Updated in the [v0.25 release ](https://github.com/rncm-prism/PRiSM-MusicGestureRecognition/releases/tag/v0.25)
